### ISSUE TITLE
[Bug] ImHex crashes when analysing any PE file

### ISSUE THREAD

**Issue by shewitt-au** [WerWolv/ImHex#2221]
### Operating System

Windows

### What's the issue you encountered?

ImHex crashes when analysing any PE file.
I also tested it on a pattern file I wrote for Commodore 64 Basic files. No crash there.

### How can the issue be reproduced?

Load a PE file.
For some reason to auto-detect doesn't work anymore, so select the PE file pattern.
The application crashes.

### ImHex Version

1.37.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

WinGet

**Comment by paxcut** [comment]
This simply cannot be true because part of the unit tests includes a PE file (pe.hexpat.exe)  that is ran against the PE pattern on every build and the unit test does not fail. I have confirmed this by manually loading the PE executable file used as a test and running the PE pattern on it without any crashes. 

Please use the attached PE executable (unzip it before opening it in ImHex) to check for crashes. If they occur then you either are using an old version of the PE pattern which needs to be updated via the content store or there are local modifications in the PE pattern file that are responsible for the crashes. If no crashes occur then provide or name a specific PE executable file that consistently crashes ImHex when the PE pattern is run on it.

[pe.hexpat.exe.zip](https://github.com/user-attachments/files/19996837/pe.hexpat.exe.zip)

**Comment by shewitt-au** [comment]
I believe ImHex sends crash dumps? It's true alright. It would seem something in my environment is a catlyst. I'm setting things up to debug it. The MSYS2 environment is new to me.

**Comment by shewitt-au** [comment]
Yes. That exe also crashes.

**Comment by paxcut** [comment]
Are you sure you are using the latest version of the PE pattern from the Content Store? If I recall correctly it has been updated recently a few times so make sure you click update if the button doesn't say delete.

**Comment by shewitt-au** [comment]
All I have now is. I'm trying to set up a better debugging enviromnet,

It's an access violation
rax=308389ef44dd5132
    
ui!ZNK3hex2ui13PatternDrawer12sortPatternsEPK19ImGuiTableSortSpecsPKN2pl4ptrn7PatternES9_+0x348:
00007ffb`d003ecf2 488b00          mov     rax,qword ptr [rax] ds:308389ef`44dd5132=????????????????

And a stack:
ui!ZNK3hex2ui13PatternDrawer12sortPatternsEPK19ImGuiTab
ui!ZNK3hex2ui13PatternDrawer12sortPatternsEPK19ImGuiTab
ui!ZN3hex2ui13PatternDrawer5resetEv+0x3f75
ui!ZN3hex2ui13PatternDrawer5resetEv+0x27e5
ui!ZN3hex2ui13PatternDrawer5resetEv+0x1367
libimhex!ZNKSt8functionIFbPKN2pl4ptrn7PatternES4_EEclES
libimhex!ZN9__gnu_cxx5__ops14_Val_comp_iterISt8function
libimhex!ZSt25__unguarded_linear_insertIN9__gnu_cxx17__
libimhex!ZSt26__unguarded_insertion_sortIN9__gnu_cxx17_
libimhex!ZSt22__final_insertion_sortIN9__gnu_cxx17__nor
libimhex!ZSt6__sortIN9__gnu_cxx17__normal_iteratorIPPN2
libimhex!ZSt4sortIN9__gnu_cxx17__normal_iteratorIPPN2pl
libimhex!ZN2pl4ptrn13PatternStruct4sortERKSt8functionIF
libimhex!ZN2pl4ptrn13PatternStruct4sortERKSt8functionIF
ui!ZNK3hex2ui13PatternDrawer17beginPatternTableERKSt6ve
ui!ZN3hex2ui13PatternDrawer4drawERKSt6vectorISt10shared
builtin!ZN3hex6plugin7builtin15ViewPatternData11drawCon
builtin!ZN3hex4View6Window4drawEv+0x10a
0x4bcc7
0x495eb
0x4980d
0xa67cd
0x16e2
0x1319
0x1426
KERNEL32!BaseThreadInitThunk+0x14
ntdll!RtlUserThreadStart+0x21

**Comment by paxcut** [comment]
This may be related to using winget to install imhex. try downloading it from github instead because the bug about sorting patterns in pattern drawer was fixed a while back and it should not exist in 1.37.4

**Comment by shewitt-au** [comment]
Ok, Downloaded from GitHub. Still crashes. Looking into your earlier suggestion to check PE pattern file.

**Comment by paxcut** [comment]
I checked myself to make sure that it isn't a new version causing the crashes and the pattern was up to date. The best debug experience i have experienced so far is using clion.

**Comment by shewitt-au** [comment]
Ok. The downloaded & installed pattern files are different:

`> Get-FileHash .\pe.hexpat

Algorithm       Hash                                                            
---------       ----                                                            
SHA256          2BF367D7BDE78615AD3FD6907320A8FD47891A31E76E8A8601761DF64969D2FF

> Get-FileHash '.\pe - new.hexpat'

Algorithm       Hash                                                            
---------       ----                                                            
SHA256          2335FB8F3FED65268872FFB60D2B2EB41AE2FE9067594933A90CD074C8D45A6E`

But the crash is still present with the new pattern.

**Comment by paxcut** [comment]
my version that doesn't crash reads:

SHA256: 2335FB8F3FED65268872FFB60D2B2EB41AE2FE9067594933A90CD074C8D45A6E

**Comment by shewitt-au** [comment]
Yeah. Same hash as I download from the pattern repo. I get a crash with both however.

**Comment by paxcut** [comment]
I recommend that you uninstall imhex completely because I have seen it keep the old executable while updating everything else.  Sometimes a full removal is the only way to getit to update properly.

**Comment by shewitt-au** [comment]
OK. Totally uninstalled. Verified that nothing was left of it. Reinstalled. Same problem (I used the new pattern file).

**Comment by paxcut** [comment]
that is very strange. You can also download nightly builds from github or even try a portable version. This crashing on pattern evaluation only happens for PE files?

**Comment by paxcut** [comment]
The PE pattern should also run on dll files. see if that also causes crashes. You can also use the coff pattern on obj files and .lib.

**Comment by shewitt-au** [comment]
Exception
---------
Thread 1 "Main" received signal SIGSEGV, Segmentation fault.
0x00007ffbcc99ecf2 in hex::ui::PatternDrawer::sortPatterns (this=0xb499950, sortSpecs=0xfdba9e0, left=0xfacc1e0, right=0x30ba9222aa5b2105) at C:/projects/ImHex/plugins/ui/source/ui/pattern_drawer.cpp:1153
1153	            result = left->getValue() <=> right->getValue();

Source at site
--------------
bool PatternDrawer::sortPatterns(const ImGuiTableSortSpecs* sortSpecs, const pl::ptrn::Pattern * left, const pl::ptrn::Pattern * right) const {
    auto result = std::strong_ordering::less;

    if (sortSpecs->Specs->ColumnUserID == ImGui::GetID("name")) {
        result = this->getDisplayName(*left) <=> this->getDisplayName(*right);
    } else if (sortSpecs->Specs->ColumnUserID == ImGui::GetID("start")) {
        result = left->getOffsetForSorting() <=> right->getOffsetForSorting();
    } else if (sortSpecs->Specs->ColumnUserID == ImGui::GetID("end")) {
        result = (left->getOffsetForSorting() + left->getSizeForSorting()) <=> (right->getOffsetForSorting() + right->getSizeForSorting());
    } else if (sortSpecs->Specs->ColumnUserID == ImGui::GetID("size")) {
        result = left->getSizeForSorting() <=> right->getSizeForSorting();
    } else if (sortSpecs->Specs->ColumnUserID == ImGui::GetID("value")) {
        result = left->getValue() <=> right->getValue(); // <--- ***Crash here***

Disassembly
-----------
1153	            result = left->getValue() <=> right->getValue();
   0x00007ffbcc99eceb <+833>:	mov    0x138(%rbp),%rax
=> 0x00007ffbcc99ecf2 <+840>:	mov    (%rax),%rax
   0x00007ffbcc99ecf5 <+843>:	add    $0x58,%rax
   0x00007ffbcc99ecf9 <+847>:	mov    (%rax),%r8
   0x00007ffbcc99ecfc <+850>:	lea    0x10(%rbp),%rax
   0x00007ffbcc99ed00 <+854>:	mov    0x138(%rbp),%rdx
   0x00007ffbcc99ed07 <+861>:	mov    %rax,%rcx
   0x00007ffbcc99ed0a <+864>:	call   *%r8
   0x00007ffbcc99ed0d <+867>:	mov    0x130(%rbp),%rax
   0x00007ffbcc99ed14 <+874>:	mov    (%rax),%rax
   0x00007ffbcc99ed17 <+877>:	add    $0x58,%rax
   0x00007ffbcc99ed1b <+881>:	mov    (%rax),%r8
   0x00007ffbcc99ed1e <+884>:	lea    0x40(%rbp),%rax
   0x00007ffbcc99ed22 <+888>:	mov    0x130(%rbp),%rdx

Call stack
----------
ui.hexpluglib!hex::ui::PatternDrawer::sortPatterns(const hex::ui::PatternDrawer * const this, const ImGuiTableSortSpecs * sortSpecs, const pl::ptrn::Pattern * left, const pl::ptrn::Pattern * right) (c:\projects\ImHex\plugins\ui\source\ui\pattern_drawer.cpp:1153)
ui.hexpluglib!operator()(const struct {...} * const __closure, const pl::ptrn::Pattern * left, const pl::ptrn::Pattern * right) (c:\projects\ImHex\plugins\ui\source\ui\pattern_drawer.cpp:1204)
ui.hexpluglib!std::__invoke_impl<bool, hex::ui::PatternDrawer::beginPatternTable(const std::vector<std::shared_ptr<pl::ptrn::Pattern> >&, std::vector<pl::ptrn::Pattern*>&, float) const::<lambda(const pl::ptrn::Pattern*, const pl::ptrn::Pattern*)>&, const pl::ptrn::Pattern*, const pl::ptrn::Pattern*>(std::__invoke_other, struct {...} &)(struct {...} & __f) (c:\msys64\mingw64\include\c++\14.2.0\bits\invoke.h:61)
ui.hexpluglib!std::__invoke_r<bool, hex::ui::PatternDrawer::beginPatternTable(const std::vector<std::shared_ptr<pl::ptrn::Pattern> >&, std::vector<pl::ptrn::Pattern*>&, float) const::<lambda(const pl::ptrn::Pattern*, const pl::ptrn::Pattern*)>&, const pl::ptrn::Pattern*, const pl::ptrn::Pattern*>(struct {...} &)(struct {...} & __fn) (c:\msys64\mingw64\include\c++\14.2.0\bits\invoke.h:114)
ui.hexpluglib!std::_Function_handler<bool(const pl::ptrn::Pattern*, const pl::ptrn::Pattern*), hex::ui::PatternDrawer::beginPatternTable(const std::vector<std::shared_ptr<pl::ptrn::Pattern> >&, std::vector<pl::ptrn::Pattern*>&, float) const::<lambda(const pl::ptrn::Pattern*, const pl::ptrn::Pattern*)> >::_M_invoke(const std::_Any_data &, const pl::ptrn::Pattern *&&, const pl::ptrn::Pattern *&&)(const std::_Any_data & __functor, const pl::ptrn::Pattern *&& __args#0, const pl::ptrn::Pattern *&& __args#1) (c:\msys64\mingw64\include\c++\14.2.0\bits\std_function.h:290)
libimhex.dll!std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)>::operator()(const std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> * const this, const pl::ptrn::Pattern * __args#0, const pl::ptrn::Pattern * __args#1) (c:\msys64\mingw64\include\c++\14.2.0\bits\std_function.h:591)
libimhex.dll!__gnu_cxx::__ops::_Val_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> >::operator()<pl::ptrn::Pattern*, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > >(__gnu_cxx::__ops::_Val_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > * const this, pl::ptrn::Pattern *& __val, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __it) (c:\msys64\mingw64\include\c++\14.2.0\bits\predefined_ops.h:240)
libimhex.dll!std::__unguarded_linear_insert<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > >, __gnu_cxx::__ops::_Val_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > >(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __last, __gnu_cxx::__ops::_Val_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > __comp) (c:\msys64\mingw64\include\c++\14.2.0\bits\stl_algo.h:1757)
libimhex.dll!std::__unguarded_insertion_sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > >(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __first, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __last, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > __comp) (c:\msys64\mingw64\include\c++\14.2.0\bits\stl_algo.h:1798)
libimhex.dll!std::__final_insertion_sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > >(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __first, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __last, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > __comp) (c:\msys64\mingw64\include\c++\14.2.0\bits\stl_algo.h:1818)
libimhex.dll!std::__sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > >(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __first, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __last, __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> > __comp) (c:\msys64\mingw64\include\c++\14.2.0\bits\stl_algo.h:1908)
libimhex.dll!std::sort<__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > >, std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> >(__gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __first, __gnu_cxx::__normal_iterator<pl::ptrn::Pattern**, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > > __last, std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> __comp) (c:\msys64\mingw64\include\c++\14.2.0\bits\stl_algo.h:4804)
libimhex.dll!pl::ptrn::PatternStruct::sort(pl::ptrn::PatternStruct * const this, const std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> & comparator) (c:\projects\ImHex\lib\external\pattern_language\lib\include\pl\patterns\pattern_struct.hpp:164)
libimhex.dll!pl::ptrn::PatternStruct::sort(pl::ptrn::PatternStruct * const this, const std::function<bool(pl::ptrn::Pattern const*, pl::ptrn::Pattern const*)> & comparator) (c:\projects\ImHex\lib\external\pattern_language\lib\include\pl\patterns\pattern_struct.hpp:167)
ui.hexpluglib!hex::ui::PatternDrawer::beginPatternTable(const hex::ui::PatternDrawer * const this, const std::vector<std::shared_ptr<pl::ptrn::Pattern>, std::allocator<std::shared_ptr<pl::ptrn::Pattern> > > & patterns, std::vector<pl::ptrn::Pattern*, std::allocator<pl::ptrn::Pattern*> > & sortedPatterns, float height) (c:\projects\ImHex\plugins\ui\source\ui\pattern_drawer.cpp:1203)
ui.hexpluglib!hex::ui::PatternDrawer::draw(hex::ui::PatternDrawer * const this, const std::vector<std::shared_ptr<pl::ptrn::Pattern>, std::allocator<std::shared_ptr<pl::ptrn::Pattern> > > & patterns, const pl::PatternLanguage * runtime, float height) (c:\projects\ImHex\plugins\ui\source\ui\pattern_drawer.cpp:1318)
builtin.hexplug!hex::plugin::builtin::ViewPatternData::drawContent(hex::plugin::builtin::ViewPatternData * const this) (c:\projects\ImHex\plugins\builtin\source\content\views\view_pattern_data.cpp:92)
builtin.hexplug!hex::View::Window::draw(hex::View::Window * const this) (c:\projects\ImHex\lib\libimhex\include\hex\ui\view.hpp:138)
hex::Window::frame(hex::Window * const this) (c:\projects\ImHex\main\gui\source\window\window.cpp:731)
hex::Window::fullFrame(hex::Window * const this) (c:\projects\ImHex\main\gui\source\window\window.cpp:238)

**Comment by paxcut** [comment]
I get it now. From your posts it seems like all you have to do  to trigger the crash is load the input file, import the pattern and evaluate the pattern.  From your last post the crash occurs in the sorting of the pattern data columns. As mentioned above this is an old bug that was fixed. So just for kicks i reordered the columns and nothing strange happened until I clicked on the value column. At that point ImHex crashed at the exact same place you posted and with the same error.

I restarted ImHex, reloaded the project, ran the pattern and no crash so far. Clicked on the value column and crash again.
It appears that what we thought of as fixed is not completely done. It also appears that in your system the value column is already selected and active so you dont need to click on the column to trigger the crash.  In either case it seems like we are getting to the bottom of this issue at last.

**Comment by paxcut** [comment]
Maybe this was never fixed? I don't remember the details but I do remember that one of the pointers was huge.

![Image](https://github.com/user-attachments/assets/6044c0ec-dc11-4528-bf6f-0adfa0af50a0)

I wasn't able to figure out why that number appeared since what is being passed are pointers that are not initialized and that get loaded valid values. If anybody remembers why the huge number was created and how to prevent it please post a note explaining it because I don't get it,

**Comment by shewitt-au** [comment]
![Image](https://github.com/user-attachments/assets/40c3f619-e17b-424f-a413-dad294a55e95)

**Comment by shewitt-au** [comment]
I'm starting to suspect memory corruption. This is in the call stack to the crash.

```
void sort(const std::function<bool (const Pattern *, const Pattern *)> &comparator) override {
            this->m_sortedMembers.clear(); // <---- Cleared. This is where the bad pointer lives
            for (auto &member : this->m_members)
            {
                if (IsBadReadPtr(member.get(), 1))
                {
                    DebugBreak(); // <------- Never hit
                }
                this->m_sortedMembers.push_back(member.get());
            }

            std::sort(this->m_sortedMembers.begin(), this->m_sortedMembers.end(), comparator);

            for (auto &member : this->m_sortedMembers)
                member->sort(comparator);
        }
```

**Comment by shewitt-au** [comment]
I believe I've got a fix.  It consists of changes to plugins/ui/source and a the subproject lib/external/pattern_language. I'm not sure how to make a PR when subprojects are in the picture. This bug was diabolical. How do I proceed?

**Comment by paxcut** [comment]
The pattern language has its own repository that you need to fork so that you can create branches and submit PRs to it. Once that one gets merged and the submodule of imhex is updated then you can post the PR to the builtin plugin code. You don't really need to wait and can PR both at same time but most likely the ImHex changes won't compile without the pattern language changes so there is little to gain by posting the imhex code.

**Comment by shewitt-au** [comment]
[PR1](https://github.com/WerWolv/PatternLanguage/pull/164)
[PR2](https://github.com/WerWolv/ImHex/pull/2242/files#diff-bb0236409276ba307f69aeae1bd5bce45fd2d864df090912d9f43e041de0a477)

PR2 has an additonal file in it from previous work. I can't figure out how to remove it. Last time I used verison control regularly SourceSafe was a thing. Sorry.

**Comment by shewitt-au** [comment]
I have added two repos to my page:
  [WriteWatch](https://github.com/shewitt-au/WriteWatch)
  [https://github.com/shewitt-au/MingW64-checked-pointer-vector](https://github.com/shewitt-au/MingW64-checked-pointer-vector)

These are the tools I wrote to verify the problem was not from external corruption.

**Comment by shewitt-au** [comment]
Is their any progress on this issue? The only build that I can run to analyse a PE file without an immediate crash is ones buld myself with the changes in the PRs linked above applied. Given the root cause of the problem I can't be the only one experiencing this issue, nor is it reasonable to assume it's only PE files that are effected. Sorry if I sound impatient.

**Comment by shewitt-au** [comment]
Is there any progress on this issue. The only versions I can run to analyse a PE file that don't immediately crash after loading the PE pattern are local build with the mods in the PRs above. Given the cause of the problem, it’s unlikely I’m the only one experiencing these issues or that they are isolated to the PE file pattern. Sorry if I sound impatient.

**Comment by WerWolv** [comment]
I guess we can merge them for now. I still want to look into the whole situation more in the future but at least fixing the crashes for now would be good

**Comment by shewitt-au** [comment]
Looks like this [issue](https://github.com/WerWolv/ImHex/issues/2152) will likely be solved my these changes.
