### ISSUE TITLE
[Bug] Issues Rearranging Toolbar Icons

### ISSUE THREAD

**Issue by vertigo220** [WerWolv/ImHex#2343]
### Operating System

Windows

### What's the issue you encountered?

Trying to rearrange the toolbar icons (and ideally it should be a simple drag-and-drop within the right pane in the options window), I tried dragging the undo and redo buttons to the left then back to put them at the end (right-most) but no matter which order I dragged them back to the right or where I dropped them, it kept putting them in the opposite order that I wanted. And I didn't even realize what was happening as I was doing it because I was so focused on trying to get them in the right order, but throughout the process of dragging them back-and-forth, it ended up removing most of the other icons on its own, so all I'm left with now is "Create new file" and undo/redo, and I can't even drag anything back over to the right anymore, even after restarting the program.

Also, unrelated to the bug, but I feel the reload icon should look like a standard refresh icon (circular arrow) which is standard in just about every other program to make it easier to identify.

### How can the issue be reproduced?

Drag icons back-and-forth between the left and right panes in Settings > Toolbar.

### ImHex Version

1.38.0.WIP

### ImHex Build Type

- [x] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Fixed the wrong icon, I believe we didn't have that icon at the time that feature was added
For the reordering - right now dragging icons on top of each other _swaps_ them instead of inserting the icon before/after the other icon. That could certainly be improved

**Comment by vertigo220** [comment]
That _might_ be what happened, as I was trying to drag them between two icons and it may have registered it as a drop _on_ one, but it doesn't explain why I can't drag any back over. I'm now stuck with just the three and can't add any others. It's not adding or swapping anymore. Though I can still _remove_ them, and now I'm down to two due to testing that. :(

**Comment by vertigo220** [comment]
How is this completed? My toolbar icons are completely broken.

**Comment by WerWolv** [comment]
I fixed it in commit 9ff8d42143e9b434c8ab92ba6bd9d9a331d59f03, is it still broken there for you?

**Comment by vertigo220** [comment]
I only saw the refresh icon was fixed in the above referenced commit. I tried redownloading the nightly to check if it's fixed but it just downloaded the same version as before.

**Comment by paxcut** [comment]
It only updates the links if all builds succeed and apparently one (for windows arm) is failing. You can still get the build from the github Actions tab

**Comment by WerWolv** [comment]
MSVC builds sadly take quite long currently. But the CI completed now so the nightlies should be updated

**Comment by paxcut** [comment]
It looks like [one ](https://github.com/WerWolv/ImHex/actions/runs/16398250326/job/46333892450) is failing

**Comment by WerWolv** [comment]
Latest commit works

**Comment by vertigo220** [comment]
I downloaded it again, and I assume it's different since the file size is different, but it's the same version # (different build number?). Anyways, it still didn't work at first, not allowing me to add icons (drag from left to right), but after messing around a bit, opening the about dialog and clicking around a bit, I went back and tried again and now it's working. Strange, but as long as it's working...

It's nice that the icons can be rearranged easily now, though it would be ideal if they could be dropped in the desired place right away as opposed to always going to the end then having to be moved again. That said, given this is something that's typically going to be done once and left alone, not sure if it's worth the effort.

Regarding copying the version, I see it is now selectable to copy, but this could still be improved. IMO a button to simply copy the info would be ideal, as it not only makes it fast and easy, but ensures all the info you need is included, e.g. the build info for nightly builds, which isn't clear what the user needs to copy to provide that info (I _assume_ it's the "master@" line, but not only am I not sure, hence why I didn't know what to provide before, but that's still not selectable and, even if it were, it would require two separate copy/paste actions).

**Comment by paxcut** [comment]
> I downloaded it again, and I assume it's different since the file size is different, but it's the same version # (different build number?). 

Version will be the same until new releases are made. The build number is sort of cryptic unless you know about git commit hashes. What makes it easy to identify the build are the build date and time. With them you can see how old the build is and to identify the exact match that somebody else may be running. Copying and pasting the date and time are already possible as you can see from the image and the result of pasting it here:
```
Compiled on Jul 20 2025 at 06:51:13
```

<img width="1791" height="656" alt="Image" src="https://github.com/user-attachments/assets/098e08f8-d6c7-4f35-9441-cbab60d06065" />

**Comment by vertigo220** [comment]
Yeah, it can be selected/copied, but my point is that for your use, when people report issues, you want to know which exact version they're using, and I suspect most people wouldn't know what info to include, not to mention that it's a bit of a hassle to have to copy/paste the version and the other info separately (admittedly, a minor one, but it's always best to minimize things like that for users both as a matter of design as well as to ensure you get all the info you want/need).

Regarding the versioning, again, from a more layman's perspective (I'm pretty familiar with GitHub and have been using it for years, and even I had difficulty with it, so I imagine many others would, though in fairness a program like this attracts more advanced users, so perhaps not as big of an issue as it would be for many others), it wasn't clear that when I redownloaded it, it was a different/updated version. At first, I thought it had just downloaded the same one again. It was only upon looking closer and comparing the sizes of the later download with the initial one that I realized they were different. It seems to me that it would make sense to version them something like 1.38.0.WIP-20250720_065113, though perhaps that isn't feasible. Just my .02 from someone not accustomed to using nightlies and relying on external sources to download.
