### ISSUE TITLE
[Bug] Cursor not aligned with interface

### ISSUE THREAD

**Issue by kjesso** [WerWolv/ImHex#302]
### Operating System

Windows

### What's the issue you encountered?

The cursor doesn't line up with the interface. I counted the pixels and the cursor needs to be 31 pixels up and 9 pixels left when in window mode and 23 pixels up when in full screen mode, in order to select the edge of menu item or the window controls (minimize, ,maximize, close). I'm running Windows 10 Pro 21H1 (OS Build 19043.1165).

### How can the issue be reproduced?

Just running the software. It happens in the latest version 1.9.0 with both the Windows MSI installer and Portable version.

### ImHex Version

1.9.0

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Hi! What resolution does the monitor you're using have? I tried reproducing it on a 1920x1080, 1680x1050 screen with x1.0 scaling and a 3000x2000 screen with x2.0 scaling and couldn't reproduce the issue myself.

**Comment by kjesso** [comment]
I tried on my laptop internal screen and external monitor with the same result:
- 1366 x 768 (internal laptop screen with scaling at 100%)
- 1920 x 1080 (external monitor screen with scaling at 100%)

My graphics card is apparently an Intel HD Graphics 4400.

**Comment by kjesso** [comment]
Also I noticed, when the "Hex editor" window is not maximized, meaning the window can be moved around, I don't have this cursor alignment issue just in this Hex editor window, but still have it on the main interface. However, as soon as I maximize the Hex editor window it then also has the same cursor alignment issue.

**Comment by masagrator** [comment]
Having similar issue. Didn't have it when running first time, but from that point I have it every time when I'm opening ImHex.
To solve it I must resize ImHex window (in any way, just one pixel).
This issue shows when there is no toolbar at the top of tool. Also then UI scaling seems broken.
Tested on 1.9.0 and 1.10.0
Windows 11, 1920x1080, OS scaling 125%

![image](https://user-images.githubusercontent.com/8557858/134326700-12ec892c-ae3a-43aa-910c-646add571d0c.png)

And after resizing window by around 1 pixel from top.
![image](https://user-images.githubusercontent.com/8557858/134326817-765fcf61-329c-48ea-acd0-bacba56ddb30.png)
Then cursor is aligned perfectly.

**Comment by rpinolf** [comment]
Similar issue here with 1.10.0 and 2160 x 1440 and 150% scaling.  I'm getting that black bar on top of the toolbar and neither resizing nor maximizing that goes away and mouse keeps unaligned.
![Captura de pantalla (4)](https://user-images.githubusercontent.com/1928372/134729824-1301fef4-47f0-4949-b5c6-ee9129c88444.png)

**Comment by avianworld** [comment]
+1 The resize action fixed it for me, thanks for the hint! @rodrigokiller 

This is a really weird issue though. The interface would be oddly blurry before the resize action

**Comment by krzychu124** [comment]
For me the last version that works correctly is v.1.8.1, anything newer has issues already described in comments above. 
I've noticed one more difference - look where buttons in the right corner are. I've tried changing Windows dpi scale to default 120% but no luck, still broken.

**v.1.9.0+** Windows Portable (within ImHex, no Windows OS controls - minimize maximize, close) - first version with

![image](https://user-images.githubusercontent.com/19638970/143718525-6caa518e-1a97-4f5e-9d07-f0109c5a401b.png)

v.1.8.1 Windows Portable (only Windows OS controls)

![image](https://user-images.githubusercontent.com/19638970/143718605-02f04d40-30f9-4c22-aa56-da5031008cac.png)

And 1.9.0 was the first version that introduced scaling options so either scaling feature or additional toolbar cause issues for some users.
![image](https://user-images.githubusercontent.com/19638970/143718640-7eb2ee73-8ab9-4933-8998-c574aa4c50c6.png)

At first glance it looks like that ImGUI still thinks that Windows OS controls are visible(vertical alignment problem) and there is space reserved for content so padding was added(horizontal alignment problem).

**Comment by WerWolv** [comment]
I potentially fixed the issue. Can somebody test to see if it works? I still cannot reproduce the issue myself on any of the ~10 computers I've tried it on

**Comment by masagrator** [comment]
Waiting for github to fix their shit as Actions are currently not working. :P

**Comment by kjesso** [comment]
Can you upload a compiled test build? I don't have my computer setup to compile the EXE or MSI.

**Comment by WerWolv** [comment]
As masagrator said, GitHub is kinda dying right now. Once it recovered itself a bit again, you can download the nightly from here: https://nightly.link/WerWolv/ImHex/workflows/build/master/Windows%20Portable%20ZIP.zip
This currently links to an old commit still though since GitHub hasn't built anything yet

**Comment by kjesso** [comment]
Same issue with that portable version you just linked to. Funny how all sub menu windows like (Help > About) works fine, but the main window has this cursor alignment issue. What is the difference between the main window and about window display?

**Comment by WerWolv** [comment]
As I just said, that link still goes to an older version. You need to wait until GitHub is fully online again so it builds the latest commit

**Comment by krzychu124** [comment]
I've tried latest version (windows portable zip) and it shows white window after splash screen and just crashes after ~1-3 sec. 
I've also checked Event viewer since I couldn't find any log files and it shows: 

Event 1000 Application error, 
Faulting application name: `imhex.exe, version: 1.10.1.0` 
Faulting module `libimhex.dll` v.0.0.0.0, 
Exception code: `0xc0000005`, 
Fault offset: `0x0000000000158979`

I see similar errors from previous sessions but with module `builtin.hexplug_unloaded` - I remember that app crashed when I disconnected external monitor and second time when I moved Windows taskbar from the side to the bottom of the screen. Pretty weird but seems to be related to screen resolution or usable screen space.

**Comment by masagrator** [comment]
The same issue as user above.

Error in event viewer is exactly the same one.

**Comment by WerWolv** [comment]
May I ask, where is your task bar exactly? On all the computers I tried it, it was at the bottom

**Comment by masagrator** [comment]
On Windows 11 you can't set anything else than bottom, so my is at the bottom.

**Comment by WerWolv** [comment]
Weird! For me everything still works completely fine with those changes...

**Comment by WerWolv** [comment]
There you go. Latest commit fixes the issue completely for @masagrator. Hopefully for all of you too :)

**Comment by krzychu124** [comment]
Thanks for all of your work but unfortunately the latest build not even launch (windows portable zip) 🙁 
I noticed that after I launched `imhex.exe` a new file appeared with name `CONERR$` and contents:
```
terminate called after throwing an instance of 'std::system_error'
  what():  cannot write to file: Bad file descriptor
``` 
but it didn't create any new folders like it was happened with previous versions (probably because of above error)

Event Viewer:

Event 1000 Application error,
Faulting application name: imhex.exe, version: 1.11.0.0
Faulting module `libstdc++-6.dll v.0.0.0.0`,
Exception code: `0x40000015`,
Fault offset: 0x000000000001cf5a

Maybe my Windows 10 compilation `19043.1387` is 'special' in bad meaning? 🤷‍♂️

**Comment by rpinolf** [comment]
I'm still having the same issue.... could this be related to some shared library not being distributed and using some different build of it collected from system dlls? Happening on a Surface Pro 3 - Windows 10 21H2 - Build 19044.1348

**Comment by WerWolv** [comment]
Well none of the standard system libraries is distributed but that should be an issue really. It works perfectly fine on my Surface Book 2 right now.

**Comment by rpinolf** [comment]
Ok...seems I'm getting something actually...it seems could be related to the screen aspect ratio rather than DPI. The SP3 at its native resolution is 2160x1440 (3:2) but switching to 1920x1080 (16:9) solves the issue. Hope this helps to narrow this down...

**Comment by WerWolv** [comment]
Well that makes it even weirder because my Surface book has a resolution of 3000x2000 which still works fine

**Comment by rpinolf** [comment]
Maybe a combination of aspect ratio and DPI maybe? Mine is at 150%. Quite sure yours as well or even over that otherwise you'll burn your eyes :-)

**Comment by WerWolv** [comment]
Yep, mine is on 150% as well. I'll try to mess around with it a bit more

**Comment by WerWolv** [comment]
Yeah so I tried it on like 10 different screen resolutions, aspect ratios and DPI scaling settings now. It looked perfect every time. I really can't tell you what's up. But it should fix itself when you resize imhex once

**Comment by rpinolf** [comment]
That's not my case. I resize the window and nothing changes. Something changed however playing with the settings, interface, scaling... trying different settings there did not solve the issue on the main window but the settings window surprisingly was well aligned. I can do a screen recording and share it with you if that could help. 
This made me think if there could be any setting in some config file that could be messing up so I cleaned up everything, so it config files were recreated in the next run, but same issues. Is there any debug setting I could enable for tracing stuff? Something that could be somewhere in the system from past builds that could interfere? This seems definitely to be related to the glfw thing...
Thanks.

**Comment by WerWolv** [comment]
Feel free to contact me on Discord if you want to further investigate with me. I can add some tracing where needed

**Comment by WerWolv** [comment]
To everybody else here, the issue could be fixed completely for @rpinolf by downloading this DLL here: https://downloads.fdossena.com/geth.php?r=mesa64-latest and placing it next to the imhex executable.
This makes everything inside ImHex be software rendered with Mesa. Please try if this fixes the issue for you as well.

**Comment by kjesso** [comment]
Yes, amazingly this DLL fixed the display issue for me. I tested it on ImHex v1.10.1.

**Comment by krzychu124** [comment]
Yes, I can confirm that software OpenGL rendering fixed issues with UI and cursor alignment (tested on latest release, windows portable). It's still wrong when I either rename or remove that dll file

**Comment by krzychu124** [comment]
In addition to that I was really curious why I need to use software acceleration if my GPU should support hardware OpenGL and turned out that the latest driver for my old integrated `Intel HD 4000` does not include drivers for OpenGL (I've read somewhere that Microsoft stopped including the OpenGL drivers when Windows 10 came out). GPU itself supports OpenGL 4.x but... probably on Linux only, since I couldn't find any Intel driver with full OpenGL support...

Since my laptop also has dedicated `nVidia GTX 660M`, **forcing to run ImHex on the dedicated GPU solves all issues for me**. It was so obvious, I don't know why I haven't tried that earlier (knowing that info would help a lot) - yes, I've tested some previous "not working" versions and all work properly when forced to run with nVidia GPU 🤦‍♂️

**Comment by espresso3389** [comment]
On Windows 11 Insider Preview Build 25151, with the MesaForWindows-x64-20.1.8.7z opengl32.dll, my window is rendered terriblly...
![image](https://user-images.githubusercontent.com/1311400/177611459-f57f8b58-b237-4ddb-9747-e1b528a83ff8.png)

**Comment by WerWolv** [comment]
Oh boy that looks terrible
On my computer ony the font looks messed up, the rest of the window looks fine. I assume you have a high DPI screen or something? afaik mesa doesn't like that a lot
