### ISSUE TITLE
macOS (fatal) GLFW Error: NSGL: The targeted version of macOS does not support OpenGL 3.0 or 3.1 but may support 3.2 and above

### ISSUE THREAD

**Issue by dreness** [WerWolv/ImHex#632]
### Operating System

MacOS

### What's the issue you encountered?

Hi! I'm on macOS 12.5 and it seems the latest macOS release build of ImHex and also the current nightly both fail the same way. From the GUI, the app just quits immediately with no comment, but if you launch it from a shell like `/Applications/imhex.app/Contents/MacOS/imhex` there is what seems like a useful error message:

```
% /Applications/imhex.app/Contents/MacOS/imhex
[17:14:36] [INFO]  [main] Welcome to ImHex!
[17:14:36] [ERROR] [main] GLFW Error [65543] : NSGL: The targeted version of macOS does not support OpenGL 3.0 or 3.1 but may support 3.2 and above
[17:14:36] [FATAL] [main] Failed to create GLFW window!
```

Looks like your [github builds target 10.10](https://github.com/WerWolv/ImHex/runs/7620422339?check_suite_focus=true#step:6:701), so I thought I'd try a local build targeting something newer, but first I'd try the same build target as a baseline.

(probably a different issue)

With a deployment target set to 10.10, I get the following build failure:

```
[  3%] Building CXX object lib/libimhex/external/pattern_language/lib/CMakeFiles/libpl.dir/source/pl/evaluator.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
In file included from /Users/andre/work/ImHex/lib/external/pattern_language/lib/source/pl/evaluator.cpp:1:
In file included from /Users/andre/work/ImHex/lib/external/pattern_language/lib/include/pl/evaluator.hpp:11:
/Users/andre/work/ImHex/lib/external/pattern_language/lib/include/pl/token.hpp:309:32: error: constexpr function's return type 'pl::Token' is not a literal type
        constexpr inline Token createToken(const pl::Token::Type type, const pl::Token::ValueTypes &value) {
                               ^
/Users/andre/work/ImHex/lib/external/pattern_language/lib/include/pl/token.hpp:303:20: note: 'Token' is not literal because it has data member 'value' of non-literal type 'pl::Token::ValueTypes' (aka 'variant<pl::Token::Keyword, pl::Token::Identifier, pl::Token::Operator, variant<char, bool, unsigned __int128, __int128, double, basic_string<char, char_traits<char>, allocator<char>>, pl::Pattern *>, pl::Token::ValueType, pl::Token::Separator>')
        ValueTypes value;
                   ^
1 error generated.
make[2]: *** [lib/libimhex/external/pattern_language/lib/CMakeFiles/libpl.dir/source/pl/evaluator.cpp.o] Error 1
make[1]: *** [lib/libimhex/external/pattern_language/lib/CMakeFiles/libpl.dir/all] Error 2
make: *** [all] Error 2
```

Attaching CMake logs incase they are useful.
[CMakeError.log](https://github.com/WerWolv/ImHex/files/9238355/CMakeError.log)
[CMakeOutput.log](https://github.com/WerWolv/ImHex/files/9238357/CMakeOutput.log)
 

### How can the issue be reproduced?

Attempt to build from source in macOS 12.5. You may have to manually fix the curl submodule build first, but that wasn't hard (I already forgot what I did, and there's no local changes in `lib/external/curl`...

### ImHex Version

trunk

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by WerWolv** [comment]
Man I would just like to say how much I hate Apple.
I'll revert those changes back on mac...

**Comment by WerWolv** [comment]
Latest commit should resolve the issue. Thanks for the report

**Comment by WerWolv** [comment]
About your build issue, you need to use gcc 12.1.0 or higher to compile ImHex currently. clang just doesn't support all the C++ features yet.

**Comment by yyogo** [comment]
@WerWolv looks like the fix is still not working on macOS:
```
[13:11:05] [INFO]  [main] Welcome to ImHex!
[13:11:06] [INFO]  [main] Native scaling set to: 1.0
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader! With GLSL: #version 130

ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader! With GLSL: #version 130

ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! With GLSL #version 130

ERROR: One or more attached shaders not successfully compiled
```

maybe you also need to revert f94b36f415056706ad4ae1af57765a213ae3cc5b?

**Comment by yyogo** [comment]
All good now, thanks!

**Comment by WerWolv** [comment]
Awesome, thanks for testing!
