### ISSUE TITLE
[BUG] Segfault When Evaluating a Custom Pattern

### ISSUE THREAD

**Issue by colejohnson66** [WerWolv/ImHex#783]
### Operating System

Windows

### What's the issue you encountered?

I entered a pattern I'm working on, and when clicking evaluate, if the syntax is valid, `libimhex.dll` attempts to dereference a null pointer.

### How can the issue be reproduced?

Currently unsure. But it's reproducible with the files and pattern I'm using.

### ImHex Version

1.24.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Running a vanilla copy. I can't share the file as it contains confidential information. I'm working on getting a debug copy built to find where in the source this is from.

Currently, what I have, from Visual Studio's debugger, is this:

> Exception thrown at 0x00007FFBC565131D (libimhex.dll) in imhex.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Call stack:

```
>	libimhex.dll!00007ffbc565131d()         Unknown
 	libimhex.dll!00007ffbc5643727()         Unknown
 	builtin.hexplug!00007ffbc108e9ae()      Unknown
 	libimhex.dll!00007ffbc52710be()         Unknown
 	libstdc++-6.dll!00007ffc2f60bf8f()      Unknown
 	libwinpthread-1.dll!00007ffc69d14b4b()  Unknown
 	msvcrt.dll!_callthreadstartex()         Unknown
 	msvcrt.dll!_threadstartex()             Unknown
 	kernel32.dll!BaseThreadInitThunk()      Unknown
 	ntdll.dll!00007ffc834adf78()            Unknown
```

**Comment by colejohnson66** [comment]
Found the location:

https://github.com/WerWolv/PatternLanguage/blob/70a31444a750fc92bf62e2ae07aff6484b226d49/lib/source/pl/core/evaluator.cpp#L47

```cpp
this->createArrayVariable(name, type.get(), dynamic_cast<ptrn::Iteratable*>(pattern.get())->getEntryCount());
```

![gdb screenshot of below text](https://user-images.githubusercontent.com/11381599/195679158-aeb993e4-90d0-4836-a927-581c14ce83c8.png)

```
Thread 15 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 22976.0x1544]
0x00007ffbbc981a02 in pl::core::Evaluator::evaluate (this=0x1bcf7435010, sourceCode=..., ast=...) at C:/msys64/home/ctobin/ImHex/lib/external/pattern_language/lib/source/pl/core/evaluator.cpp:472
472     C:/msys64/home/ctobin/ImHex/lib/external/pattern_language/lib/source/pl/core/evaluator.cpp: No such file or directory.
```

**Comment by colejohnson66** [comment]
When I was writing the pattern, it would complain about syntax errors. So, I know that's not it; the file is syntactically correct. All I have to do now to get it to trigger is to open one of our files, paste the pattern, then click the evaluate button. The progress indicator will spin for a second before locking up and crashing.

This is my first pattern, so I'm still learning and may be doing something wrong. Here's an extract from the file:

```
#pragma endian little

// https://github.com/WerWolv/ImHex-Patterns/blob/6cb208d975d86d09c81742dbf7bfff96734b5180/patterns/id3.hexpat#L23
struct SevenBitInt
{
    u8 bytes[4];
} [[sealed, format("sbi_value"), transform("sbi_value")]];

fn sbi_value(ref SevenBitInt n)
{
    u32 result = 0;
    for (u8 i = 0, i < 4, i = i + 1) {
        u8 b = n.bytes[i] & 0x7F;
        u8 shamt = 7 * (4 - i - 1);
        result = result | (b << shift);
    }
    return result;
};

struct String
{
    SevenBitInt Length;
    u8 data[Length];
} [[sealed]];

struct DateTime
{
    s64 Ticks;
} [[sealed, static]];
```

**Comment by WerWolv** [comment]
Fixed the issue thank you!
It could occur when creating global `char` or `char16` arrays. The latest commit should correct this now

**Comment by colejohnson66** [comment]
Whelp, no it didn't fix it... I can email you the `hexpat` file if needed.

**Comment by WerWolv** [comment]
If you can, yes please. You can also find me on discord with the handle WerWolv#1337

**Comment by colejohnson66** [comment]
PEBKAC. I forgot to pull submodules when I pulled.
